- [ ] Does app run as non-root user?
- [ ] APP does run as PID 1, or it does have a proper handler for signals and
      child process (if any).
- [ ] Does app update any dependency? needs to update Dockerfile because of
      this?
- [ ] Compile/debug information and tools are not included in the final
      docker image
