# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: docker/compose:1.23.1

      # These other images will be running in parallel, and they will
      # be exposed on the same machine (i.e., you can access to them
      # using localhost:port.
      # - image: circleci/postgres:9.4

    steps:
      - checkout

      # This create a REMOTE docker engine!
      - setup_remote_docker

      - run: docker-compose build
      - run:
          command: docker-compose up
          background: true

      # Need to use a container in the network to communicate with app container
      - run: while ! docker-compose exec answer_svc apk add --no-cache netcat-openbsd; do :; done
      - run: docker-compose exec answer_svc sh -c "echo ls | nc app 9999"

